# verify if 2 values had same memory location
COURSE_NAME = "Python bootcamp"
COURSE_TITLE = COURSE_NAME
SOME_VALUE = 46
ANOTHER_VALUE = 45
RESULT_VALUE = ANOTHER_VALUE + 1

# IS
print(
    f"COURSE_TITLE {COURSE_TITLE} is SOME_VALUE {SOME_VALUE}: ",
    COURSE_TITLE is SOME_VALUE,
)
# false

print(
    f"SOME_VALUE {SOME_VALUE} is RESULT_VALUE {RESULT_VALUE}: ",
    SOME_VALUE is RESULT_VALUE,
)
# false

print(
    f"COURSE_NAME {COURSE_NAME} is COURSE_TITLE {COURSE_TITLE}: ",
    COURSE_NAME is COURSE_TITLE,
)
# true

# IS NOT
print(
    f"COURSE_NAME {COURSE_NAME} is NOT COURSE_TITLE {COURSE_TITLE}: ",
    COURSE_NAME is not COURSE_TITLE,
)
# false
